export const EXAMPLE_CORPUS_FILES = [
  "docs/examples/architecture.drum",
  "docs/examples/combined-hits.drum",
  "docs/examples/common-16th.drum",
  "docs/examples/common-cross-stick.drum",
  "docs/examples/common-ghost.drum",
  "docs/examples/common-half-time.drum",
  "docs/examples/common-open-hh.drum",
  "docs/examples/common-rock.drum",
  "docs/examples/common-shuffle.drum",
  "docs/examples/common-triplet-fill.drum",
  "docs/examples/full-example.drum",
  "docs/examples/groups.drum",
  "docs/examples/hairpins.drum",
  "docs/examples/headers.drum",
  "docs/examples/inline-repeat.drum",
  "docs/examples/modifiers.drum",
  "docs/examples/multi-rest.drum",
  "docs/examples/musicxml.drum",
  "docs/examples/overview.drum",
  "docs/examples/repeats.drum",
  "docs/examples/sticking.drum",
  "docs/examples/tokens.drum",
  "docs/examples/tracks.drum",
  "docs/examples/validation.drum",
  "examples/你要跳舞吗.drum",
  "examples/李白-李荣浩.drum",
] as const;

export type ExampleCorpusFile = (typeof EXAMPLE_CORPUS_FILES)[number];
